## BE SURE TO RUN `go generate` and commit the changes when changing
rules:
  - name: whitelist
    terms:
      - whitelist
      - white-list
    alternatives:
      - allowlist
    severity: warning

  - name: blacklist
    terms:
      - blacklist
      - black-list
    alternatives:
      - denylist
      - blocklist
    severity: warning
