on:
  release:
    types:
      - created

name: Documentation refresh

jobs:
  build:
    name: Renew documentation
    runs-on: ubuntu-latest
    steps:
    - name: Pull new module version
      uses: andrewslotin/go-proxy-pull-action@v1.0.0
    - name: Pull new module version
      uses: andrewslotin/go-proxy-pull-action@v1.0.0
      with:
        goproxy: https://gocenter.io
