on:
  release:
    types:
      - created
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

name: documentaion refresh

jobs:
  build:
    name: Renew documentation
    runs-on: ubuntu-latest
    steps:
    - name: Pull new module version
      uses: andrewslotin/go-proxy-pull-action@v1.0.0
    - name: Pull new module version
      uses: andrewslotin/go-proxy-pull-action@v1.0.0
      with:
        goproxy: https://gocenter.io
